esphome:
  name: playphone
  comment: Téléphone compteur d'histoire
  platformio_options:
    board_build.filesystem: littlefs
  on_boot:
    priority: 600
    then:
      - delay: 2s
      - media_player.volume_set:
          id: phone_player
          volume: 0.15
      - media_player.volume_set:
          id: web_player
          volume: 0.02
      - media_player.repeat_one:
          id: phone_player


audio_file:
  - id: beep
    file: playphone_wave/001_occupe.wav

media_source:
  - platform: audio_file
    id: file_source

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf


psram:
  mode: octal
  speed: 80MHz



# Enable logging
logger:


# Enable Home Assistant API
api:
    encryption:
        key: !secret playphone_api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  min_auth_mode: WPA2
  power_save_mode: none
  post_connect_roaming: false
  ssid: !secret wifi_ssid
  password: !secret wifi_password



http_request:
  verify_ssl: false

# =========================
# I2S
# =========================

i2s_audio:
  - id: i2s_out
    i2s_lrclk_pin: GPIO11
    i2s_bclk_pin: GPIO10

# =========================
# MAX98357A
# =========================

speaker:
  - platform: i2s_audio
    id: phone_speaker
    dac_type: external
    i2s_dout_pin: GPIO12
    channel: mono
    timeout: never

# =========================
# Media Player
# =========================

media_player:
  - platform: speaker_source
    name: "Phone Player"
    id: phone_player
    volume_max: 0.3
    announcement_pipeline:
      speaker: phone_speaker
      sources:
        - file_source
   

  - platform: speaker
    id: web_player
    name: "Music Player"
    announcement_pipeline:
      speaker: phone_speaker



globals:
  - id: reading_intro
    type: bool
    initial_value: 'false'




text_sensor:
  - platform: wifi_info
    mac_address:
      internal: true
      id: mac_address_sensor
  - platform: template
    internal: true
    id: device_id_sensor
    lambda: |-
      std::string mac = id(mac_address_sensor).state;
      mac.erase(std::remove(mac.begin(), mac.end(), ':'), mac.end());
      return mac;

binary_sensor:
  - platform: gpio
    id: rotary_active
    name: "rotary active"
    internal: true
    pin:
      number: GPIO4
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 10ms
    on_press: #début de la rotation
      then:
       - pulse_meter.set_total_pulses:
          id: mypulse_meter
          value: 0
    on_release: # fin de la rotation
      then:
      - logger.log:
          format: "Select %.0f"
          args: [ 'id(mytotal).state' ]
          level: INFO
      - media_player.stop:
            id: phone_player
      - media_player.play_media:
           id: web_player
           media_url: !lambda |-
                          return "http://coyote.lan:3233/sound/0"
                                 + std::to_string((int) id(mytotal).state)
                                 + "?device_key="
                                 + id(device_id_sensor).state;

  - platform: gpio
    id: hangup
    name: "Hangup"
    pin:
      number: GPIO5
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 10ms
    on_release: # Raccroche
      then:
        - media_player.stop:
            id: web_player
        - http_request.get:
            url: !lambda |-
              return std::string("http://coyote.lan:3233/hangup?device_key=")
                     + id(device_id_sensor).state;
        - delay: 100ms
        - media_player.stop:
            id: phone_player
        - lambda: |-
              id(reading_intro) = false;
    on_press: # Décroche
      then:
        - media_player.play_media:
            media_url: "audio-file://beep"
            id: phone_player
        - http_request.get:
            url: !lambda |-
              return std::string("http://coyote.lan:3233/pickup?device_key=")
                     + id(device_id_sensor).state;




sensor:
  - platform: pulse_meter
    id: mypulse_meter
    internal_filter: 10ms
    timeout: 500ms
    internal: true
    total:
      name: "Total Pulses"
      internal: true
      id: mytotal
    pin:
      number: GPIO6
      mode:
        input: true
        pullup: true

  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
